artifact_location: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652
creation_time: 1779002083427
experiment_id: '359401235209162652'
last_update_time: 1779002083427
lifecycle_stage: active
name: Data_Engine_Ingestion
