artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/a1a2c0054e8840f9bb5db8598d6305cc/artifacts
end_time: 1779002088919
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: a1a2c0054e8840f9bb5db8598d6305cc
run_name: Phase 4 - Fully Optimized Schema & Encodings
source_name: ''
source_type: 4
source_version: ''
start_time: 1779002087798
status: 3
tags: []
user_id: vibhu
