artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/409e7de10ff045a09501245aae0fddce/artifacts
end_time: 1779029350627
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: 409e7de10ff045a09501245aae0fddce
run_name: abrasive-wolf-546
source_name: ''
source_type: 4
source_version: ''
start_time: 1779029348274
status: 3
tags: []
user_id: vibhu
