artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/f982abf7d4bf4a23a00a6be670f84265/artifacts
end_time: 1779017692692
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: f982abf7d4bf4a23a00a6be670f84265
run_name: stylish-horse-131
source_name: ''
source_type: 4
source_version: ''
start_time: 1779017691988
status: 3
tags: []
user_id: vibhu
