artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/8df2349f517b4dbc940f890b5af4ca7e/artifacts
end_time: 1779026169167
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: 8df2349f517b4dbc940f890b5af4ca7e
run_name: fun-carp-941
source_name: ''
source_type: 4
source_version: ''
start_time: 1779026165659
status: 3
tags: []
user_id: vibhu
