artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/eaef64b8fbc540148be941b7e84089d8/artifacts
end_time: 1779017657294
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: eaef64b8fbc540148be941b7e84089d8
run_name: monumental-worm-922
source_name: ''
source_type: 4
source_version: ''
start_time: 1779017656232
status: 3
tags: []
user_id: vibhu
