artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/fadc793dfd0c40c0afe762e4472a2764/artifacts
end_time: 1779017829602
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: fadc793dfd0c40c0afe762e4472a2764
run_name: skillful-perch-362
source_name: ''
source_type: 4
source_version: ''
start_time: 1779017828846
status: 3
tags: []
user_id: vibhu
