artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/cdcb2cade5c14b0d824cc957f319d912/artifacts
end_time: 1779029588736
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: cdcb2cade5c14b0d824cc957f319d912
run_name: amusing-sow-739
source_name: ''
source_type: 4
source_version: ''
start_time: 1779029586302
status: 3
tags: []
user_id: vibhu
