artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/9eab3cdcf896434dab4a54f7f67327bf/artifacts
end_time: 1779025335436
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: 9eab3cdcf896434dab4a54f7f67327bf
run_name: spiffy-mule-700
source_name: ''
source_type: 4
source_version: ''
start_time: 1779025332273
status: 3
tags: []
user_id: vibhu
