artifact_location: file:///E:/singularity Intern Project/main_folder/mlflow_data/281814155892373597
creation_time: 1779003067756
experiment_id: '281814155892373597'
last_update_time: 1779003067756
lifecycle_stage: active
name: Data_Engine_Benchmarks
