artifact_location: file:///E:\singularity Intern Project\main_folder\mlflow_data/224794592159160920
creation_time: 1778772094064
experiment_id: '224794592159160920'
last_update_time: 1779004120517
lifecycle_stage: deleted
name: NIFTY_Data_Engine_Internship
tags: {}
