artifact_uri: file:///E:/singularity Intern Project/main_folder/mlflow_data/359401235209162652/2db9f4f2c1f44d6496a2dd0b8fdb3718/artifacts
end_time: 1779026276840
entry_point_name: ''
experiment_id: '359401235209162652'
lifecycle_stage: active
run_id: 2db9f4f2c1f44d6496a2dd0b8fdb3718
run_name: exultant-bee-8
source_name: ''
source_type: 4
source_version: ''
start_time: 1779026274109
status: 3
tags: []
user_id: vibhu
